import { SidebarNavItem } from '@/types'

export const navItems: SidebarNavItem[] = [
  {
    slug: 'dashboard',
    title: 'داشبورد',
    href: '/dashboard',
    icon: 'dashboard',
    label: '',
    authorized: [],
  },
  {
    slug: 'article',
    title: 'مقالات',
    href: '/dashboard/articles',
    icon: 'stickyNote',
    label: '',
    authorized: [
      'article.view.any',
      'article.view.own',
      'articleComment.view.own',
    ],
  },
  {
    slug: 'article-comment',
    title: 'نظرات',
    href: '/dashboard/article-comments',
    icon: 'stickyNote',
    label: '',
    authorized: ['articleComment.moderate.any', 'articleComment.view.any'],
  },
  {
    slug: 'user',
    title: 'کاربران',
    href: '/dashboard/users',
    icon: 'user',
    label: '',
    authorized: ['user.view.any', 'user.view.own'],
    // sub: [
    //   {
    //     slug: 'employee',
    //     title: 'کارمندان',
    //     href: '/dashboard/users/employees',
    //     icon: 'employee',
    //     label: '',
    //     authorized: ['.view.any', '.view.own'],,
    //   },
    //   {
    //     slug: 'employee',
    //     title: 'کارمندان',
    //     href: '/dashboard/users/employees',
    //     icon: 'employee',
    //     label: '',
    //     authorized: ['.view.any', '.view.own'],,
    //   },
    // ],
  },
  {
    slug: 'category',
    title: 'دسته بندی ها',
    href: '/dashboard/categories',
    icon: 'category',
    label: '',
    authorized: ['category.view.any', 'category.view.own'],
  },
  {
    slug: 'tag',
    title: 'برچسب‌ها',
    href: '/dashboard/tags',
    icon: 'tag',
    label: '',
    authorized: ['tag.view.any', 'tag.view.own'],
  },
  {
    slug: 'menu',
    title: 'فهرست ها',
    href: '/dashboard/menus',
    icon: 'squareMenu',
    label: '',
    authorized: ['menu.view.any', 'menu.view.own'],
  },
  {
    slug: 'page',
    title: 'برگه‌ ها',
    href: '/dashboard/pages',
    icon: 'layoutTemplate',
    label: '',
    authorized: ['page.view.any', 'page.view.own'],
  },
  {
    slug: 'campaign',
    title: 'کمپین ها',
    href: '/dashboard/campaigns',
    icon: 'megaphone',
    label: '',
    authorized: ['campaign.view.any', 'campaign.view.own'],
  },

  {
    slug: 'template',
    title: 'قالب ها',
    href: '/dashboard/templates',
    icon: 'layoutTemplate',
    label: '',
    authorized: ['template.view.any', 'template.view.own'],
  },
  {
    slug: 'template-part',
    title: 'قطعه قالب',
    href: '/dashboard/template-parts',
    icon: 'layoutTemplate',
    label: '',
    authorized: ['template.view.any', 'template.view.own'],
  },
  {
    slug: 'settings',
    title: 'تنظیمات',
    href: '/dashboard/settings/general',
    icon: 'slidersVertical',
    label: '',
    authorized: [
      'settings.view.any',
      'settings.view.own',
      'settings.moderate.any',
    ],
  },

  {
    slug: 'logout',
    title: 'خروج',
    href: '/logout',
    icon: 'login',
    label: '',
    authorized: [],
  },
]
