import { Icons } from '@/components/icons'
import { NavItem, SidebarNavItem } from '@/types'

export const navItems: SidebarNavItem[] = [
  {
    slug: 'dashboard',
    title: 'داشبورد',
    href: '/dashboard',
    icon: 'dashboard',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'article',
    title: 'مقالات',
    href: '/dashboard/articles',
    icon: 'stickyNote',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'article-comment',
    title: 'نظرات',
    href: '/dashboard/article-comments',
    icon: 'stickyNote',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'user',
    title: 'کاربران',
    href: '/dashboard/users',
    icon: 'user',
    label: '',
    authorized: ['admin'],
    // sub: [
    //   {
    //     slug: 'employee',
    //     title: 'کارمندان',
    //     href: '/dashboard/users/employees',
    //     icon: 'employee',
    //     label: '',
    //     authorized: ['admin'],
    //   },
    //   {
    //     slug: 'employee',
    //     title: 'کارمندان',
    //     href: '/dashboard/users/employees',
    //     icon: 'employee',
    //     label: '',
    //     authorized: ['admin'],
    //   },
    // ],
  },
  {
    slug: 'category',
    title: 'دسته بندی ها',
    href: '/dashboard/categories',
    icon: 'category',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'tag',
    title: 'برچسب‌ها',
    href: '/dashboard/tags',
    icon: 'tag',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'menu',
    title: 'فهرست ها',
    href: '/dashboard/menus',
    icon: 'squareMenu',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'page',
    title: 'برگه‌ ها',
    href: '/dashboard/pages',
    icon: 'layoutTemplate',
    label: '',
    authorized: ['admin'],
  },

  {
    slug: 'template',
    title: 'قالب ها',
    href: '/dashboard/templates',
    icon: 'layoutTemplate',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'template-part',
    title: 'قطعه قالب',
    href: '/dashboard/template-parts',
    icon: 'layoutTemplate',
    label: '',
    authorized: ['admin'],
  },
  {
    slug: 'settings',
    title: 'تنظیمات',
    href: '/dashboard/settings',
    icon: 'slidersVertical',
    label: '',
    authorized: ['admin'],
  },

  {
    slug: 'logout',
    title: 'خروج',
    href: '/logout',
    icon: 'login',
    label: '',
  },
]
