import './initial-load'
import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import { Session } from '@/types'
import { getSession } from '@/lib/auth'
import { Providers } from './providers'

const iransans = localFont({
  src: [
    {
      path: '../public/fonts/IRANSansX-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/IRANSansX-Medium.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/IRANSansX-DemiBold.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-iransans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = (await getSession()) as Session
  // console.log('#23409798 session:', session)
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={iransans.className}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  )
}
